version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: tic_tac_toe_db
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tictactoe
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./client/.env
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tic_tac_toe_backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["npm", "start"]

volumes:
  postgres_data:
