name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Verify repository structure
        run: ls -R
        working-directory: .

      - name: Install dependencies for client
        run: npm install
        working-directory: client

      - name: Install dependencies for server
        run: npm install
        working-directory: server

      - name: Run client tests
        run: npm test
        working-directory: client

      - name: Run server tests
        run: npm test
        working-directory: server
