name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies for both client and server
      - name: Install dependencies for client
        run: npm install
        working-directory: tic-tac-toe-pro/client

      - name: Install dependencies for server
        run: npm install
        working-directory: tic-tac-toe-pro/server

      # Run tests for both client and server
      - name: Run client tests
        run: npm test
        working-directory: tic-tac-toe-pro/client

      - name: Run server tests
        run: npm test
        working-directory: tic-tac-toe-pro/server
